package it.unibo.distributedfrp.simulation.environment

/**
 * A factory for generating [[Environment]]s for FRASP simulations.
 * @tparam E the type of the [[Environment]]s generated by this [[EnvironmentFactory]].
 */
@FunctionalInterface
trait EnvironmentFactory[+E <: Environment]:
  /** @return a new [[Environment]] generated by this [[EnvironmentFactory]]. */
  def newInstance(): E
